development:
  password: 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
  theme_id: '118815981723'
  store: pc-for-you.myshopify.com
  ignore_files:
    - "*.gif"
    - "*.jpg"
    - "*.github"
    - "*.env"
    - "*.gitignore"
    - "*.theme-check"
    - "package.json"
    - "config/settings_data.json"
    - "node_modules/*"
