version: 2.1
jobs:
  build:
    docker: 
      - image: circleci/node:12

    working_directory: ~/repos

    steps:
      - checkout
      - restore_cache:
          # Find a cache corresponding to those specific yarn.lock and .yarnclean checksums
          # when these files are changed, this key will fail
          key: v3-npm-deps-{{ arch }}-{{ checksum "yarn.lock" }}-{{ checksum ".yarnclean" }}
      - run: yarn
      - save_cache:
          key: v3-npm-deps-{{ arch }}-{{ checksum "yarn.lock" }}-{{ checksum ".yarnclean" }}
          paths:
            - node_modules
      # Stylelint Code
      - run: 
          name: test scss
          command: yarn stylelint
      # Lint Code
      - run: 
          name: test js
          command: yarn lint:js
      # DEPLOY: Upload Theme to Shopify
      - run: 
          name: deploy to Shopify
          command: yarn deploy