# This is a basic workflow to help you get started with Actions

name: Shopify-CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: 
      - master
  push:
    branches: 
      - master

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    name: Build + Deploy Preview
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          os:
            - ubuntu-latest
          node_version:
            - 12

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Use Node.js 12.x
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}

      - name: Set up Ruby 2.7.x
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.x

      - name: Use Yarn 1.17.2
        run: |
          npm install -g yarn@1.17.2
          yarn
      - name: theme check Locales
      # ver si este punto funcion, sino crear otro directorio
        run: |
          gem install theme-check
          theme-check ./src
        
      - name: Lint Theme Config Files
        run: |
          npm i -g jsonlint-tree
          jsonlint-tree src/config

      - name: Zip Theme
        run: node .github/workflows/scripts/theme-zip.js

      - name: Delete existing PR Theme
        run: node .github/workflows/scripts/theme-delete.js 
        env:
          SHOP_NAME: ${{secrets.SECRET_SHOP_NAME}}
          API_KEY: ${{secrets.SECRET_API_KEY}}
          API_PASSWORD: ${{secrets.SECRET_API_PASSWORD}}
          GITHUB_REPOSITORY: ${{secrets.SECRET_GIT_REPOSITORY}}
          GITHUB_EVENT_PATH: ${{secrets.SECRET_EVENT_PATH}}
          GITHUB_SHA: ${{secrets.SECRET_SHA}}
          GITHUB_REF: ${{secrets.SECRET_GIT_REF}}

      - name: Upload Theme to Shopify One
        run: |
          node .github/workflows/scripts/theme-upload.js
          node .github/workflows/scripts/theme-check.js

        env:
          SHOP_NAME: ${{secrets.SECRET_SHOP_NAME}}
          API_KEY: ${{secrets.SECRET_API_KEY}}
          API_PASSWORD: ${{secrets.SECRET_API_PASSWORD}}
          NGROK_AUTH_TOKEN: ${{secrets.SECRET_NGROK_AUTH_TOKEN}}
          GITHUB_REPOSITORY: ${{secrets.SECRET_GIT_REPOSITORY}}
          GITHUB_EVENT_PATH: ${{secrets.SECRET_EVENT_PATH}}
          GITHUB_SHA: ${{secrets.SECRET_SHA}}
          GITHUB_TOKEN: ${{secrets.SECRET_GIT_TOKEN}}
          GITHUB_REF: ${{secrets.SECRET_GIT_REF}}